fee_calc/models.py
import persistent


class Fee(persistent.Persistent):

    def __init__(self, payee, acceptor, balance, description):
        super().__init__()
        self.payee = payee
        self.acceptor = acceptor
        self.balance = balance
        self.description = description

    def __str__(self):
        return "{}\t=> {}: {}".format(self.acceptor, self.payee, self.balance)

    def as_dict(self):
        return self.__dict__

fee_calc/blueprints/back.py
from fee_calc.database import db
from fee_calc.models import Fee
from fee_calc.reducer import generate_list, generate_report, generate_reduced_report
from flask import Blueprint, g, jsonify, redirect, request, url_for


blueprint = Blueprint('back', __name__.split('.')[0])


@blueprint.route('/api/root_user', methods=['GET'])
def root_user():
    return jsonify(g.root_user)


@blueprint.route('/api/users', methods=['GET'])
def users():
    return jsonify(g.users)


@blueprint.route('/api/list', methods=['GET'])
def list():
    return jsonify(generate_list())


@blueprint.route('/api/report', methods=['GET'])
def report():
    return jsonify(generate_report())


@blueprint.route('/api/summarized_report', methods=['GET'])
def summarized_report():
    return jsonify(generate_reduced_report())


@blueprint.route('/api/send_fee', methods=['GET'])
def send_fee():
    payee = request.args.get('payee')
    acceptor = request.args.get('acceptor')
    balance = float(request.args.get('balance'))
    description = request.args.get('description')
    with db.engine.transaction() as c:
        c.root.fees.append(Fee(payee, acceptor, balance, description))
    return redirect(url_for('front.front'))

fee_calc/blueprints/front.py
from flask import Blueprint
from flask import g, render_template


blueprint = Blueprint('front', __name__.split('.')[0])


@blueprint.route('/')
def front():
    return render_template('front.html', users=g.users)

fee_calc/templates/front.html
<!-- DOCTYPE -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>fee-calc</title>
    <meta charset="utf-8">
    <!-- Viewport Meta Tag -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

  </head>
  <body>
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1>fee-calc</h1>
            <p>Please fill the form!</p>
        </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <form id="form" action="{{ url_for('back.send_fee') }}">
            <fieldset class="form-group">
            <label for="payee">Payee</label>
            <select class="form-control" id="payee" name="payee">
                <option></option>
                {% for user in users %}
                <option>{{ user }}</option>
                {% endfor %}
            </select>
            </fieldset>
            <fieldset class="form-group">
            <label for="acceptor">Acceptor</label>
            <select class="form-control" id="acceptor" name="acceptor">
                <option></option>
                {% for user in users %}
                <option>{{ user }}</option>
                {% endfor %}
            </select>
            </fieldset>
            <fieldset class="form-group">
            <label for="balance">Balance</label>
            <input type="text" class="form-control" id="balance" name="balance">
            </fieldset>
            <fieldset class="form-group">
            <label for="balance">Description</label>
            <textarea class="form-control" rows="5" id="description" name="description"></textarea>
            </fieldset>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
        </div>


        <div class="col-md-6">
            <h1>List</h1>
            <div id="list"></div>
        </div>
      </div>

      <div class="row">
          <div class="col-md-12">
            <hr>
          </div>
      </div>

      <div class="row">
          <div class="col-md-6">
            <h1>Report</h1>
            <div id="report"></div>
          </div>

          <div class="col-md-6">
            <h1>Reduced report</h1>
            <div id="summarized_report"></div>
          </div>
      </div>
    </div>
    <footer class="footer">
      <div class="container">
        <span class="text-muted">@morfeush22</span>
      </div>
    </footer>

    <!-- JavaScript: placed at the end of the document so the pages load faster -->
    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>

    <!-- Tether -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

     <!-- Latest React -->
    <script src="https://unpkg.com/react@latest/dist/react.js"></script>
    <script src="https://unpkg.com/react-dom@latest/dist/react-dom.js"></script>
    <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script type="text/babel" src="{{ url_for('static', filename='local.js') }}"></script>
    <script type="text/babel" src="{{ url_for('static', filename='rest.js') }}"></script>
  </body>
</html>